import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { check } from '@/lib/service-db';
import { ActionForm } from '@/components/action-form';
import { logout, saveName, removeSearch } from '@/app/actions';
import { PushControls } from '@/components/push-controls';
export const metadata = { title: 'Мой кабинет', robots: { index: false } };
function searchUrl(f: Record<string, unknown>) { const p = new URLSearchParams(); for (const [k, v] of Object.entries(f))
    if (v !== null && v !== '' && v !== false && k !== 'page')
        p.set(k, v === true ? '1' : String(v)); return '/jobs?' + p; }
export default async function Profile() { const { client, user } = await requireUser(); const { data: p } = check(await client.from('profiles').select('*').eq('id', user.id).single()); const { data: searches } = check(await client.from('saved_searches').select('*').eq('user_id', user.id).order('created_at', { ascending: false }).limit(50)); const { data: notifications } = check(await client.from('notifications').select('*').eq('user_id', user.id).order('created_at', { ascending: false }).limit(30)); return <><h1>Мой кабинет</h1><nav><Link className="button" href="/favorites">Избранное</Link><Link className="button" href="/employer">Мои вакансии</Link><Link className="button" href="/profile/password">Сменить пароль</Link>{p.roles.includes('admin') && <Link className="button" href="/admin">Админка</Link>}<form action={logout}><button>Выйти</button></form></nav><hr className="divider"/><section className="panel"><h2>Профиль</h2><p className="small muted">{user.email}</p><ActionForm action={saveName}><label>Как к вам обращаться<input name="display_name" maxLength={100} defaultValue={p.display_name} placeholder="Ваше имя"/></label></ActionForm><hr className="divider"/><h2>Сохранённые поиски</h2><p className="small muted">Показаны последние 50 поисков.</p>{searches?.length ? searches.map(s => <div className="data-row" key={s.id}><div className="row"><Link href={searchUrl(s.filters)}>{s.name} →</Link><span className="small muted">{s.notify ? 'Уведомления включены' : 'Без уведомлений'}</span><form action={removeSearch}><input type="hidden" name="id" value={s.id}/><button>Удалить поиск</button></form></div></div>) : <p>Сохраните первый поиск в каталоге вакансий.</p>}<hr className="divider"/><PushControls publicKey={process.env.PUSH_PUBLIC_KEY || ''}/><h2>Последние уведомления</h2>{notifications?.length ? notifications.map(n => <div className="data-row" key={n.id}><Link href={n.url}>{n.title}</Link><p className="small muted">{new Date(n.created_at).toLocaleString('ru-RU')}</p></div>) : <p className="muted">Пока нет уведомлений.</p>}</section></>; }
