import test from 'node:test';
import assert from 'node:assert/strict';
import { friendly } from '../../lib/validation.ts';
import { z } from 'zod';
test('invalid login credentials распознаётся', () => assert.equal(friendly({ message: 'Invalid login credentials', code: 'invalid_credentials' }), 'Неверный email или пароль.'));
test('email_not_confirmed понятен пользователю', () => assert.match(friendly({ message: 'Email not confirmed', code: 'email_not_confirmed' }), /email ещё не подтверждён/i));
test('повторная регистрация ведёт ко входу', () => assert.match(friendly({ message: 'User already registered', code: 'user_already_exists' }), /уже зарегистрирован.*войдите/is));
test('слабый пароль объясняется', () => assert.match(friendly({ message: 'Password should be at least 10 characters', code: 'weak_password' }), /слишком простой/i));
test('лимит писем объясняется', () => assert.match(friendly({ message: 'Over email sending rate limit', code: 'over_email_send_rate_limit' }), /слишком много писем/i));
test('redirect url не разрешён — подсказка про конфигурацию', () => assert.match(friendly({ message: 'Invalid redirect to https://evil.example', code: 'invalid_redirect_to' }), /Redirect URLs/i));
test('недействительный API key — конфигурация', () => assert.match(friendly({ message: 'Invalid API key' }), /конфигурации сервера/i));
test('отсутствующий служебный ключ виден как конфигурация', () => assert.match(friendly({ message: 'Не настроена переменная SUPABASE_SERVICE_ROLE_KEY' }), /Не настроена переменная SUPABASE_SERVICE_ROLE_KEY/));
test('сетевая ошибка понятна', () => assert.match(friendly({ message: 'fetch failed' }), /Нет связи/));
test('ошибка PostgREST не выдаётся за данные пользователя', () => assert.match(friendly({ message: 'PGRST202: Could not find the function' }), /Ошибка базы данных/));
test('RATE_LIMIT сохраняет прежнее сообщение', () => assert.match(friendly({ message: 'RATE_LIMIT' }), /слишком много попыток/i));
test('duplicate key сохраняет прежнее сообщение', () => assert.match(friendly({ message: 'duplicate key value violates unique constraint' }), /уже существует/));
test('Zod показывается как проверка полей', () => { const r = z.string().email().safeParse('not-an-email'); assert.equal(r.success, false); assert.match(friendly(r.error), /Проверьте поля/); });
test('NEXT_REDIRECT пробрасывается дальше', () => assert.throws(() => friendly({ digest: 'NEXT_REDIRECT;push;/profile;307;' })));
test('неизвестная ошибка не обещает, что данные введены неверно', () => assert.equal(friendly({ message: 'something strange happened' }), 'Не удалось выполнить действие. Попробуйте ещё раз. Если ошибка повторяется, обратитесь к администратору.'));